import Link from 'next/link';

const items = [
 {id:'coverage',title:'Industrial Maintenance Coverage',desc:'Qualified industrial maintenance support for manufacturers that need additional hands without immediately adding permanent headcount. Coverage can be scheduled for blocks of time, full shifts, weekly needs, shutdowns, temporary staffing gaps, or longer-term assignments.', bullets:['Scheduled block-of-time and full-shift maintenance coverage','Mechanical, electrical, and electromechanical troubleshooting and repair','Breakdown response, production-line support, inspections, and PM execution','Temporary coverage for vacancies, vacations, leaves, hiring gaps, or high workload periods','Longer-term assignments for sustained maintenance capacity','Coverage structured around expected hours, schedule, skill requirements, travel, and duration']},
 {id:'contract-pm',title:'Contract Preventive Maintenance',desc:'Recurring preventive maintenance support for manufacturers that want a defined PM workload executed on a contractual basis. Agreements are built around your equipment, PM frequency, expected labor hours, and contract duration.', bullets:['Monthly, quarterly, shutdown, or custom PM coverage','Scheduled PM execution, inspections, lubrication and condition checks','Maintenance backlog reduction and recurring machine inspections','Contract totals developed from estimated hourly labor requirements across the agreement']},
 {id:'breakdown',title:'Industrial Troubleshooting & Repair',desc:'When a machine or production line is down, unreliable, or creating repeat problems, we use a structured process to isolate the failure and restore operation safely.', bullets:['Mechanical, electrical, sensor, motor, and drive troubleshooting','Symptom verification and fault isolation','Production-line and machine breakdown support','Temporary recovery vs. permanent repair recommendations','Documented findings and follow-up actions']},
 {id:'cnc',title:'CNC & Machine Tool Support',desc:'Hands-on support for CNC machines and the systems around them. Olmem Technical Services is an independent maintenance provider, not an OEM service center.', bullets:['Mechanical and auxiliary equipment troubleshooting','Pumps, coolant systems, conveyors, motors and drives','Fault isolation and restart support','Condition assessment for older or newly purchased machines']},
 {id:'pm-development',title:'Maintenance Program Development',desc:'Need help building the PM program itself? We can review the equipment, identify maintenance needs, create or improve PM tasks, and establish a practical schedule before ongoing coverage begins.', bullets:['New PM creation and existing PM review','PM frequency and labor-hour estimating','Lubrication, wear, alignment and condition checks','Work instructions, task lists and maintenance documentation']},
 {id:'assessment',title:'Equipment Assessments & Punch Lists',desc:'For unclear equipment situations, acquisitions, startups, aging assets, or maintenance backlogs, we can turn unknowns into an organized, prioritized action list.', bullets:['Equipment assessment and punch-list development','Priority ranking by safety, startup impact and risk','Parts, tooling, documentation and specialist-support needs','Job planning and maintenance backlog development']},
 {id:'shutdown',title:'Shutdown & Project Maintenance Support',desc:'Additional maintenance capacity for planned outages, installations, startups, repairs, and project work where your internal team needs more hands on the floor.', bullets:['Planned shutdown maintenance and inspections','Equipment installation and startup support','Backlog reduction and focused repair campaigns','Short-term project assignments and supplemental maintenance labor']}
];

export const metadata = { title:'Industrial Maintenance Services', description:'Industrial maintenance coverage, contract preventive maintenance, troubleshooting, CNC support, shutdown support, maintenance program development, and equipment assessments.' };
export default function Services(){return <><section className="page-hero"><div className="container"><span className="eyebrow">SERVICES</span><h1>Industrial maintenance capacity for the hours, shifts, and projects your facility needs.</h1><p>Olmem Technical Services provides hands-on maintenance coverage for manufacturers that need qualified help keeping equipment running. Support can range from a single scheduled shift to recurring PM work, shutdown coverage, troubleshooting, or longer-term assignments.</p></div></section><section className="section"><div className="container service-detail-list">{items.map(i=><article id={i.id} className="service-detail" key={i.id}><div><span className="eyebrow dark">CAPABILITY</span><h2>{i.title}</h2><p>{i.desc}</p></div><ul className="check-list">{i.bullets.map(b=><li key={b}>{b}</li>)}</ul></article>)}</div></section><section className="section alt"><div className="container split"><div><span className="eyebrow dark">MAINTENANCE COVERAGE PRICING</span><h2>Coverage built from the hours and schedule your operation requires.</h2><p className="lead">Industrial maintenance coverage can be structured around a block of hours, designated shifts, a temporary assignment, shutdown period, or longer contract term.</p><p>The scope is developed from the expected labor hours, shift schedule, required skills, travel, assignment duration, and type of work involved. That allows the customer to receive a clear contract or term-based price while keeping the coverage tied to the actual maintenance capacity required.</p><p>Recurring PM agreements can be priced the same way, using the estimated maintenance hours needed across the duration of the contract.</p></div><div className="feature-panel"><span className="panel-label">A TYPICAL PROCESS</span><ol className="number-list"><li><b>01</b><span><strong>Define the coverage.</strong> Identify the shift, schedule, equipment, responsibilities, skills, and duration.</span></li><li><b>02</b><span><strong>Estimate the hours.</strong> Determine the expected labor requirement and any travel or special support needs.</span></li><li><b>03</b><span><strong>Build the agreement.</strong> Convert the expected hours into a block, weekly, monthly, shutdown, or term-based contract.</span></li><li><b>04</b><span><strong>Execute the work.</strong> Provide troubleshooting, repairs, PMs, inspections, and day-to-day maintenance support as defined by the assignment.</span></li></ol></div></div></section><section className="cta-section"><div className="container cta-wrap"><div><h2>Need another qualified maintenance technician on the floor?</h2><p>Send the shift, expected hours, duration, equipment involved, and type of maintenance support you need.</p></div><Link href="/contact" className="button button-light">Request Maintenance Coverage</Link></div></section></>}
